export const MAX_RETRIES = 2;
export const RETRY_FALLBACK_MS = 1000;
export const SESSION_RESOLVE_RETRY_MS = 75;

export const DEFAULT_MAX_TOOL_HISTORY_LENGTH = 30;
export const DEFAULT_MAX_STATUS_MESSAGE_LENGTH = 1700;
export const DEFAULT_ORPHAN_TTL_MS = 5 * 60 * 1000;
export const DEFAULT_CLEANUP_DELAY_MS = 1000;
export const DEFAULT_AGENT_END_DELAY_MS = 1500;
export const DEFAULT_MAX_DISPLAY_MS = 10 * 60 * 1000;
export const DELETE_RECOVERY_DELAY_MS = 5_000;

export const ORPHAN_TTL_MS = DEFAULT_ORPHAN_TTL_MS;
export const STATUS_MAX_LENGTH = DEFAULT_MAX_STATUS_MESSAGE_LENGTH;
export const STATUS_MAX_ENTRIES = 6;
export const STATUS_MAX_SUBAGENT_ENTRIES = 3;
export const CLEANUP_DELAY_MS = DEFAULT_CLEANUP_DELAY_MS;
export const AGENT_END_DELAY_MS = DEFAULT_AGENT_END_DELAY_MS;
